version: 2.1

jobs:
  build:
    macos:
      xcode: "10.2.1"
    working_directory: ~/grakn
    steps:
      - checkout
      - run: sleep 1h
workflows:
  version: 2
  build:
    jobs:
      - build

