# circleci config

jobs:
  build:
    - run: |
        bazel run @graknlabs_grabl//correctness:start -- --test test-A --org $CIRCLE_ORG --repo $CIRCLE_REPO --job-id $CIRCLE_JOB_ID
        bazel build //...
        bazel run @graknlabs_grabl//correctness:success -- --test test-A --org $CIRCLE_ORG --repo $CIRCLE_REPO --job-id $CIRCLE_JOB_ID
  deploy-github:
    - run: echo "deploy github"
  grabl-correctness-completed:
    run: |
      bazel run @graknlabs_grabl//correctness:completed -- --org $CIRCLE_ORG --repo $CIRCLE_REPO
  grabl-release-completed:
    run: |
      bazel run @graknlabs_grabl//release:completed -- --org $CIRCLE_ORG --repo $CIRCLE_REPO

workflows:
  common:
    jobs:
      - build
      - grabl-correctness-completed:
          requires:
            - build

  common-release-branch:
    jobs:
      - deploy-github
      - grabl-release-completed:
          requires:
            - deploy-github